rc:
  ref: main
  deployed_at: "2025-07-05T16:13:42Z"
  deployed_by: kmrok
stg:
  ref: v0.0.1
  deployed_at: "2025-07-05T16:07:36Z"
  deployed_by: kmrok
prd:
  ref: v0.0.1
  deployed_at: "2025-07-05T16:08:55Z"
  deployed_by: kmrok
