rc:
  ref: main
  deployed_at: "2025-07-14T01:08:04Z"
  deployed_by: kmrok
stg:
  ref: v0.0.2
  deployed_at: "2025-07-05T18:08:57Z"
  deployed_by: kmrok
prd:
  ref: v0.0.1
  deployed_at: "2025-07-05T17:46:44Z"
  deployed_by: kmrok
