rc:
  ref: main
  deployed_at: "2025-07-05T17:58:11Z"
  deployed_by: kmrok
stg:
  ref: v0.0.1
  deployed_at: "2025-07-05T17:06:47Z"
  deployed_by: kmrok
prd:
  ref: v0.0.1
  deployed_at: "2025-07-05T17:46:44Z"
  deployed_by: kmrok
