name: "Deploy to RC"

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "デプロイ対象のブランチ"
        required: true

permissions:
  contents: write

concurrency:
  group: deploy
  cancel-in-progress: false

jobs:
  check-branch-exists:
    uses: ./.github/workflows/reusable-check-ref-exists.yaml
    with:
      ref: ${{ github.event.inputs.ref }}
      ref-type: branch

  notify-deployment-start:
    needs: check-branch-exists
    uses: ./.github/workflows/reusable-slack-notify.yaml
    with:
      type: start
      environment: "rc"
      branch: ${{ github.event.inputs.ref }}
      actor: ${{ github.actor }}
      workflow: ${{ github.workflow }}
    secrets: inherit

  deploy:
    needs: notify-deployment-start
    uses: ./.github/workflows/reusable-build-and-deploy.yaml
    with:
      node-version: '18'
      aws-region: ap-northeast-1
      s3-folder-name: "folder"
      build-output: "./dist/hoge.js" # TODO: ここを変える
      environment: "rc"
    secrets: inherit

  notify-deployment-failure:
    needs: deploy
    if: failure()
    uses: ./.github/workflows/reusable-slack-notify.yaml
    with:
      type: failure
      environment: "rc"
      branch: ${{ github.event.inputs.ref }}
      actor: ${{ github.actor }}
      workflow-run-url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
    secrets: inherit

  notify-deployment-success:
    needs: deploy
    if: success()
    uses: ./.github/workflows/reusable-slack-notify.yaml
    with:
      type: success
      environment: "rc"
      branch: ${{ github.event.inputs.ref }}
      actor: ${{ github.actor }}
      workflow-run-url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
    secrets: inherit

  update-release-file:
    needs: deploy
    if: success()
    uses: ./.github/workflows/reusable-update-release-file.yaml
    with:
      environment: "rc"
      ref: ${{ github.event.inputs.ref }}
      actor: ${{ github.actor }}
    secrets: inherit
