name: "Reusable Build and Deploy to S3"
description: "Build Node.js project and deploy to S3 (reusable workflow)"

on:
  workflow_call:
    inputs:
      node-version:
        description: "Node.js version to use"
        required: true
        type: string
      aws-region:
        description: "AWS Region"
        required: false
        type: string
        default: "ap-northeast-1"
      s3-folder-name:
        description: "S3 folder path (e.g., 'releases/v1.0')"
        required: true
        type: string
      build-directory:
        description: "Build output directory"
        required: false
        type: string
        default: "./dist"
      enable-cache:
        description: "Enable npm cache (npm, yarn, pnpm, or empty to disable)"
        required: false
        type: string
        default: ""
      environment:
        description: "Environment name for deployment"
        required: false
        type: string
        default: ""
    secrets:
      AWS_ACCESS_KEY_ID:
        description: "AWS Access Key ID"
        required: true
      AWS_SECRET_ACCESS_KEY:
        description: "AWS Secret Access Key"
        required: true
      S3_BUCKET_NAME:
        description: "S3 bucket name for deployment"
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: "Setup Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: ${{ inputs.enable-cache }}
      # - name: "Install dependencies"
      #   run: npm install
      #   shell: bash
      # - name: "Build project"
      #   run: npm run build
      #   shell: bash
      - name: "Configure AWS credentials"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws-region }}
      - name: "Deploy to S3"
        run: |
          aws s3 sync ${{ inputs.build-directory }} "s3://${{ secrets.S3_BUCKET_NAME }}/${{ inputs.s3-folder-name }}" --delete
          echo "✅ Deployment to S3 completed: s3://${{ secrets.S3_BUCKET_NAME }}/${{ inputs.s3-folder-name }}"
        shell: bash
